version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/aws-ec2-test
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
