name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: test Docker
        run: docker run hello-world