name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Stop docker
        run: docker-compose stop

      - name: Build docker
        run: docker-compose build

      - name: Start docker
        run: docker-compose up -d