name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: /home/ubuntu/app

jobs:
  continuous-deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Copy repo
        run: cp -a /home/ubuntu/actions-runner/_work/aws-ec2-test/aws-ec2-test/. .

      - name: Stop docker
        run: docker-compose stop

      - name: Build docker
        run: docker-compose build

      - name: Start docker
        run: docker-compose up -d